#!/usr/bin/env bash
# Build Musique as a Release .app and package it into a distributable DMG.
#
# Usage:
#   ./scripts/build-dmg.sh                 # defaults to build/dmg/
#   ./scripts/build-dmg.sh /path/to/out    # custom output dir
#
# Requires: Xcode + hdiutil (built-in).
# Optional: xcodegen (regenerates xcodeproj if project.yml changed),
#           xcbeautify (prettier build log).

set -euo pipefail

# --- Configuration ---------------------------------------------------------

PROJECT="Musique.xcodeproj"
SCHEME="Musique"
CONFIGURATION="Release"
APP_NAME="Musique"
OUTPUT_DIR="${1:-build/dmg}"
BUILD_DIR="build/derived"
STAGING_DIR="build/staging"

# Resolve repo root regardless of caller's cwd.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR/.."

# --- Helpers ---------------------------------------------------------------

log() { printf "\033[1;34m==>\033[0m %s\n" "$*"; }
err() { printf "\033[1;31m!!\033[0m %s\n" "$*" >&2; }

# --- Regenerate project ----------------------------------------------------

# Inject Last.fm secrets from env vars (if provided) into Secrets.xcconfig.
# Either export the vars before invoking the script, or fill in
# Secrets.xcconfig by hand. Empty values build a working app but Last.fm
# scrobbling requires the user to enter their own API credentials in Settings.
if [[ -n "${LASTFM_API_KEY:-}" || -n "${LASTFM_API_SECRET:-}" ]]; then
    log "Writing Last.fm secrets from environment into Secrets.xcconfig"
    cat > Secrets.xcconfig <<EOF
// Auto-generated by scripts/build-dmg.sh. Do not commit.
LASTFM_API_KEY = ${LASTFM_API_KEY:-}
LASTFM_API_SECRET = ${LASTFM_API_SECRET:-}
EOF
fi

if command -v xcodegen >/dev/null 2>&1 && [[ -f project.yml ]]; then
    log "Regenerating $PROJECT via xcodegen"
    xcodegen generate
fi

# --- Clean previous artifacts ---------------------------------------------

log "Cleaning previous artifacts"
rm -rf "$BUILD_DIR" "$STAGING_DIR"
mkdir -p "$OUTPUT_DIR" "$STAGING_DIR"

# --- Build -----------------------------------------------------------------

log "Building $SCHEME ($CONFIGURATION)"
if command -v xcbeautify >/dev/null 2>&1; then
    set -o pipefail
    xcodebuild \
        -project "$PROJECT" \
        -scheme "$SCHEME" \
        -configuration "$CONFIGURATION" \
        -derivedDataPath "$BUILD_DIR" \
        -destination 'generic/platform=macOS' \
        clean build \
        | xcbeautify
else
    xcodebuild \
        -project "$PROJECT" \
        -scheme "$SCHEME" \
        -configuration "$CONFIGURATION" \
        -derivedDataPath "$BUILD_DIR" \
        -destination 'generic/platform=macOS' \
        clean build
fi

APP_PATH="$BUILD_DIR/Build/Products/$CONFIGURATION/$APP_NAME.app"
if [[ ! -d "$APP_PATH" ]]; then
    err "Build succeeded but $APP_PATH was not produced."
    exit 1
fi

# Version comes from the *built* app: the source Info.plist holds
# $(MARKETING_VERSION), which only becomes a number once Xcode has substituted it.
VERSION="$(plutil -extract CFBundleShortVersionString raw -o - "$APP_PATH/Contents/Info.plist" 2>/dev/null || echo "dev")"
DMG_NAME="${APP_NAME}-${VERSION}.dmg"
DMG_PATH="${OUTPUT_DIR}/${DMG_NAME}"
log "Packaging version $VERSION"

# --- Stage -----------------------------------------------------------------

log "Staging $APP_PATH"
cp -R "$APP_PATH" "$STAGING_DIR/"
# Drag-to-install convenience: a symlink to /Applications.
ln -s /Applications "$STAGING_DIR/Applications"

# --- Package DMG -----------------------------------------------------------

log "Creating $DMG_PATH"
rm -f "$DMG_PATH"
hdiutil create \
    -volname "$APP_NAME $VERSION" \
    -srcfolder "$STAGING_DIR" \
    -ov \
    -format UDZO \
    -fs HFS+ \
    "$DMG_PATH" >/dev/null

# --- Optional: codesign + notarize ----------------------------------------
# Uncomment and configure if you have a Developer ID account.
#
# DEV_ID="Developer ID Application: Your Name (TEAMID)"
# log "Code-signing DMG"
# codesign --sign "$DEV_ID" --timestamp "$DMG_PATH"
#
# log "Notarizing (this can take several minutes)"
# xcrun notarytool submit "$DMG_PATH" \
#     --keychain-profile "AC_PASSWORD" \
#     --wait
# xcrun stapler staple "$DMG_PATH"

# --- Done ------------------------------------------------------------------

log "Done"
ls -lh "$DMG_PATH"
echo
echo "Install: open '$DMG_PATH' → drag $APP_NAME to Applications."
